from gym_taco_environments.envs.bandits.v0.bandits import TwoArmedBanditEnv as TwoArmedBanditEnvV0
from gym_taco_environments.envs.frozen_lake.v0.frozen_lake import FrozenLakeEnv as FrozenLakeEnvV0
from gym_taco_environments.envs.frozen_lake.v1.frozen_lake import FrozenLakeEnv as FrozenLakeEnvV1
from gym_taco_environments.envs.robot_battery.v0.robot_battery import RobotBatteryEnv as RobotBatteryEnvV0
